name: 'g++-11 installation test'

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: add-apt-repo
        uses: tecoli-com/actions-install-and-cache@v0
        with:
          cache: workflow
          sudo: true
          command: add-apt-repository -y
          target: ppa:ubuntu-toolchain-r/test
          path: /etc/apt /var/lib/apt /var/lib/waagent
      - run: sudo apt update
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: g++-11
          method: timestamp
      - run: |
          g++-11 --version
      - run: test "${{ steps.action.outputs.cache-hit }}" != true

  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: add-apt-repo
        uses: tecoli-com/actions-install-and-cache@v0
        with:
          cache: workflow
          sudo: true
          command: add-apt-repository -y
          target: ppa:ubuntu-toolchain-r/test
          path: /etc/apt /var/lib/apt /var/lib/waagent
      - run: sudo apt update
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: g++-11
          method: timestamp
      - run: |
          g++-11 --version
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
