name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: workflow
          packages: bmake
      - run: |
          bmake hasta-la-vista || true
  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: workflow
          packages: bmake
      - run: bmake hasta-la-vista || true
  no-cache:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: no
          packages: bmake
      - run: bmake hasta-la-vista || true
  cache-gen:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          cache: workflow
          packages: bmake
          cache_gen: v2
      - run: bmake hasta-la-vista || true
